### ISSUE TITLE
Haze se cierra luego de un error

### ISSUE THREAD

**Issue by FenixBlack1030** [enzosanchezc/haze#13]
Hola, vengo usando el programa desde hace rato, pero  desde hace unos días (22 dic), no me funciona o funciona MUY de vez en cuando, tirando un error y cerrándose. Ya intenté descargarlo nuevamente, borrar los archivos y dejando solo el .exe y volviendo a ingresar los datos, pero el error persiste.
![Sin título](https://user-images.githubusercontent.com/60514167/209417619-d03e34b0-9f82-4f17-afd2-5b549c93c922.png)

Luego de ingresar mi usuario y contraseña, tira ese error y se cierra. Luego, si lo vuelvo a iniciar, abre la ventana durante unos segundos y se vuelve a cerrar. Estoy usando la versión 0.10.1, aunque he probado otras y se da el mismo caso. La única versión que no pude probar es la 0.11, ya que intenté compilarla y no supe hacerlo correctamente.

**Comment by FenixBlack1030** [comment]
otros datos que me olvidé mencionar es que en el archivo log, luego de lo mencionado mas arriba dice "ERROR root 'str' object has no attribute 'get'" y el archivo user queda en blanco incluso luego de ingresar los datos en la aplicación.

**Comment by enzosanchezc** [comment]
Hola, disculpá la demora, al rededor de esa fecha hubo problemas del lado de Steam, probablemente por la sale que hubo. Ahora se solucionó?
