### ISSUE TITLE
No inicia sesión ni guarda el archivo de configuración

### ISSUE THREAD

**Issue by mariano-andres-horianski** [enzosanchezc/haze#14]
Un día de estos dejó de iniciar sesión automáticamente el programa y muestra esto cada vez que pongo mis datos:

![Sin título](https://user-images.githubusercontent.com/76558204/209546549-ca48e502-d2d8-4bda-9f51-c6799fdc5767.png)

Intenté acceder desde mi navegador al link de la API que te da la lista de juegos que ya tenés para ver si no tengo un ban con la API de steam o algo así pero anda todo bien.

**Comment by enzosanchezc** [comment]
Hola, disculpá no me llegan notificaciones de Github, al rededor de esa fecha fue la sale de Steam y estuvo teniendo problemas con los logins. Debería estar solucionado.
