### ISSUE TITLE
Problemas al compilar

### ISSUE THREAD

**Issue by fede2010** [enzosanchezc/haze#24]
Hola, estoy teniendo problemas para compilar la aplicación, al momento de ejecutarla se abre y se cierra. Entonces la abrí desde el CMD y tiene el siguiente error:

![image](https://github.com/enzosanchezc/haze/assets/50007922/cea26e9a-e2ce-4f93-a179-7584020d10e6)

Tengo instalada la ultima version de python 3.11.4 y este es el archivo warn-haze que se creo por si acaso
[warn-Haze.txt](https://github.com/enzosanchezc/haze/files/12208768/warn-Haze.txt)

**Comment by Init0ne** [comment]
> Hola, estoy teniendo problemas para compilar la aplicación, al momento de ejecutarla se abre y se cierra. Entonces la abrí desde el CMD y tiene el siguiente error:
> 
> ![image](https://user-images.githubusercontent.com/50007922/257040858-cea26e9a-e2ce-4f93-a179-7584020d10e6.png)
> 
> Tengo instalada la ultima version de python 3.11.4 y este es el archivo warn-haze que se creo por si acaso [warn-Haze.txt](https://github.com/enzosanchezc/haze/files/12208768/warn-Haze.txt)

Desinstala python e instala la version 3.11.3, a mi me funciono

**Comment by fede2010** [comment]
Gracias, con eso se soluciono y compilo lo mas bien
